openapi: '3.0.3'
info:
  title: Quotation API 
  description: Get a quote online
  version: '1.0'
  contact:
    email: bayer@predic8.de
servers:
  - url: https://api.server.test/v1
tags:
  - name: Quote
paths:
  /rfqs:
    post:
      tags:
        - Quote
      description: Request a quote
      operationId: getQuote
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Quotation"
      responses:
        '201':
          description: OK

components:
  schemas:
    Quotation:
      type: object
      properties:
        id:
          type: string
          format: uuid
        product:
          type: string
          maxLength: 20
          pattern: '(\w+\W*)*'
          example: Firecracker
        quantity:
          type: integer
          format: int32
          minimum: 0
          maximum: 1000
        price:
          type: number
          minimum: 0
          example: 1.99
        shipment:
          type: string
          enum:
            - FOB
            - DAT
        mode:
          type: string
          pattern: "[A-Z]{3}"
          maxLength: 3