openapi: '3.0.3'
info:
  title: Quotation API 
  description: Get a quote online
  version: '1.0'
  contact:
    email: bayer@predic8.de
servers:
  - url: https://api.server.test/v1
tags:
  - name: Quote
paths:
  /rfqs:
    post:
      tags:
        - Quote
      description: Request a quote
      operationId: getQuote
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Quotation"
      responses:
        '777':
          description: OK

components:
  schemas:
    Quotation:
      type: object
      properties:
        id:
          type: integer
        product:
          type: string
        quantity:
          type: integer
        price:
          type: number
        shipment:
          type: string
        mode:
          type: string