name: OpenAPI Checks

on:
  - pull_request

jobs:
  build:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: stoplightio/spectral-action@latest
      - name: Archive Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: openapi-linting-report
          path: report.txt
