name: OpenAPI Checks

on:
  - pull_request

jobs:
  build:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Node Setup
        uses: actions/setup-node@v3
      - run: npm install --save -D @stoplight/spectral-owasp-ruleset
      - uses: actions/checkout@v3
      - uses: stoplightio/spectral-action@latest
